# -*- coding: utf-8 -*-
"""Итоговое задание.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RzpaSOyeLoveJ-1DKu6S5jYYtMnP6RlL
"""

import pandas as pd

df_city = pd.read_sql(
"""
SELECT 
  name
FROM
  City
WHERE
  country_code = 'RUS' AND name like 'Adler'  ;
""",
"postgresql://netology:NetoSQL2019@84.201.153.170:19001/world-db"
)
df_city.head(100)

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

df = pd.read_csv('holiday.csv', sep =',')

df.head()

df.rename(columns = {'Города_англ' : 'name_en'}, inplace = True)
df.head()

df1= df[['Страна','Город', 'name_en']]
df1.head()

df_city = pd.read_sql(
"""
SELECT 
  name , population
FROM
  City;
""",
"postgresql://netology:NetoSQL2019@84.201.153.170:19001/world-db"
)
df_city.head()

df2= df1.merge(df_city,left_on='name_en', right_on='name', how = 'inner')
df2.head(10)

df2.groupby(['Страна']).mean()